### ISSUE TITLE
Better Centrifuges or add Recipes in other Mods

### ISSUE THREAD

**Issue by LuziferSenpai** [JDKDigital/productive-bees#451] opened 2024-01-03 04:10 UTC
It would be awesome if we could get some better Centrifuges or Mods like Thermal, GregTech etc. could get Honey Comb Recipes.

Yea the Heated Centrifuge is fast, but not fast enough.

**Comment by Nekosity12** [comment] 2024-01-03 04:23
Are you using comb blocks? The heated centrifuge is 3x faster than the powered centrifuge, but effectively 12x faster since it can also process comb blocks. You can always make a few more if one isn't enough with it processing blocks.

There are recipes in other mods, look up create mixer. There's also an expansion mod made by someone else that introduces faster centrifuges: https://www.curseforge.com/minecraft/mc-mods/centrifuge-tiers-reproduced

**Comment by LuziferSenpai** [comment] 2024-01-03 08:14
I already use the Heated, but with Industrial Foregoing Souls together with Omega Upgrades it barely keeps up with about 60+ Heated Centrifuges.

**Comment by Nekosity12** [comment] 2024-01-03 11:51
What are you using industrial foregoing souls on, beehives? Because if so you're going beyond the intended balance point at that point & it's more a pack issue to resolve than a mod issue. Afaik, I believe the speed can be adjusted via config, and as mentioned before there is an expansion mod that adds tiers above heated. Ofc the pack can also always just disable accelerating them from what I've seen of the industrial foregoing souls mod page.

Keep in mind I'm not the dev so I don't make the final decision here or anything, my opinion on it is totally irrelevant if Jonn thinks differently lol

**Comment by JaisDK** [comment] 2024-01-03 12:55
I'm guessing you're playing ATM9 since you have GT. I'm pretty sure the pack devs are working on adding comb processing to GT centrifuges.
I won't be adding any further processing in the base mod so it's up to the pack to either make the centrifuges fast or add other ways of processing them.

**Closed as completed** 2024-01-04 21:30 UTC
