### ISSUE TITLE
[1.16.4] Tag was used before it was bound (ticking entity)

### ISSUE THREAD

**Issue by Gbergz** [JDKDigital/productive-bees#140] opened 2021-01-12 10:31 UTC
Title^

**Forge Version**
35.1.36 - 1.16.4

**Log file / crash report**
https://hatebin.com/qdqhjnmysq

**Describe the issue**
_Someone from my discord reported this and describes it like this:_
``When I do a right click anywhere on a block ( chest, door ,furnace and other ) I crash and I have this error``

**Comment by JaisDK** [comment] 2021-01-12 10:33
I don't use that tag, it must be another mods mixin or event handler.

**Comment by JaisDK** [comment] 2021-01-12 10:47
The tag is added by BloodMagic. It looks like they forgot to namespace it. https://github.com/WayofTime/BloodMagic/blob/1.16.3/src/main/java/wayoftime/bloodmagic/common/tags/BloodMagicTags.java#L22

**Comment by WayofTime** [comment] 2021-01-12 13:26
By namespace I assume you mean I didn't do "bloodmagic:life". Will that fix this crash?

**Comment by JaisDK** [comment] 2021-01-12 13:32
I would expect it to be in your own namespace otherwise it will be in "minecraft". I'm not sure what is causing the crash though, traced it to something like public net.minecraft.entity.Entity::updateEyesInWater

**Comment by JaisDK** [comment] 2021-01-12 13:33
Try sticking a bee in blood and see if it crashes, I can't think of any other situation where updateEyesInWater would be called :)

**Comment by WayofTime** [comment] 2021-01-12 13:45
The vanilla bees can fly properly in the blood even when I don't use the proper formatting for the tag. Even placed a few flowers. Does it need to be the bees from your mod?

**Comment by JaisDK** [comment] 2021-01-12 13:46
I don't override that method, but I can try and load up your mod and see. Give me 5-10 minutes

**Comment by JaisDK** [comment] 2021-01-12 14:22
No crash here either. Looks like one of those shite errors that are not reproduceable outside of the players world. I can see that you do have a json file for the tag, so I don't see a problem in your code.

**Comment by JaisDK** [comment] 2021-01-12 14:23
Another thing, @Gbergz I just assumed that the crash was from TNP Limitless 3 so I looked through the mods in my local instance, but Blood Magic is not in the crash log. Was it recently added or removed?

**Comment by JaisDK** [comment] 2021-01-12 14:27
Not seeing Productive Bees either :S Is that modlist just useless and incomplete or did the player remove mods?

**Comment by WayofTime** [comment] 2021-01-12 14:30
Maybe it's an incomplete crash log. Gberz, could you upload the full log file?

**Comment by Gbergz** [comment] 2021-01-12 15:57
I didn't have the full log since a player sent the crash to me. 

Modlist here https://www.curseforge.com/minecraft/modpacks/tnp-limitless-3/files/3164238

**Closed** 2021-01-13 07:20 UTC
